name             'opengov-users'
maintainer       'The OpenGov Foundation'
maintainer_email 'developers@opengovfoundation.org'
license          'CC0'
description      'Installs/Configures user accounts'
long_description 'Installs/Configures user accounts'
version          '0.1.6'

depends 'chef-vault'
depends 'sudo'
